# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JdMlrbt0PDXr0qI2KEVo5kxyveK0y_0X
"""

import pandas as pd
import matplotlib.pyplot as plt

# Load the smartwatch data from the CSV file
data = pd.read_csv('Smartwatch_data.csv')

# Convert the 'Date' column to datetime
data['Date'] = pd.to_datetime(data['Date'])

# Set the 'Date' column as the index
data.set_index('Date', inplace=True)

# Group the data by week starting on Monday
data_by_week = data.groupby(pd.Grouper(freq='W-MON')).sum().reset_index()

# Calculate the total number of steps taken per week
steps_per_week = data_by_week['Steps']

# Calculate the total distance travelled per week (assuming an average stride length of 0.75 meters)
distance_per_week = steps_per_week * 0.75 / 1000

# Calculate the total number of calories burnt per week
calories_per_week = data_by_week['Calories']

# Calculate the average amount of sleep per week
sleep_per_week = data_by_week['Sleep'] / 7

# Plot the data
fig, (ax1, ax2, ax3, ax4) = plt.subplots(nrows=4, sharex=True, figsize=(10, 8))

ax1.plot(data_by_week['Date'], steps_per_week, 'o-')
ax1.set_ylabel("Steps")

ax2.plot(data_by_week['Date'], distance_per_week, 'o-')
ax2.set_ylabel('Distance (km)')

ax3.plot(data_by_week['Date'], calories_per_week, 'o-')
ax3.set_ylabel('Calories')

ax4.plot(data_by_week['Date'], sleep_per_week, "o-")
ax4.set_ylabel('Sleep (hours)')

# Set the x-axis ticks to be the week numbers
ax4.set_xticks(data_by_week['Date'])
ax4.set_xticklabels(data_by_week['Date'].dt.strftime('%Y-%W'), rotation=45)

# Set the title and labels
plt.suptitle('Smartwatch Data by Week')
plt.xlabel('Week Number')

# Show the plot
plt.tight_layout(rect=[0, 0, 1, 0.96])
plt.show()